name: Check for lint/build errors
on:
  pull_request:
    branches:
      - "**"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          node-version: lts_latest

      - name: yarn install, lint
        run: |
          yarn install
          yarn run lint
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          node-version: lts_latest

      - name: install & build
        run: |
          yarn install
          yarn run build
