name: Run automated tests
on:
  pull_request:
    branches:
      - main
      - beta
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: yarn install, test
        run: |
          yarn install
          yarn test
