name: Run automated tests
on:
  pull_request:
    branches:
      - main
      - beta
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: npm install, test
        run: |
          npm install
          npm test
